### ISSUE TITLE
RunTime Errror

### ISSUE THREAD

**Issue by AjaxR0** [Uplodading-Team/Guren#3]
> ^C^CTraceback (most recent call last):
  File "botstart.py", line 72, in <module>
    bot.run(TOKEN)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 637, in run
    _cleanup_loop(loop)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 92, in _cleanup_loop
    _cancel_tasks(loop)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 77, in _cancel_tasks
    loop.run_until_complete(asyncio.gather(*tasks, return_exceptions=True))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 482, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

Happens upon CTRL+C execution.

**Comment by AjaxR0** [comment]
Fixed
